/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppAsset {
  'assetId' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'description' : string,
  'updatedAt' : Time,
  'assetCategory' : string,
}
export interface BannerConfig {
  'height' : bigint,
  'backgroundColor' : string,
  'objectFit' : string,
  'enabled' : boolean,
  'updatedAt' : Time,
  'destinationUrl' : string,
  'bannerImage' : [] | [ExternalBlob],
  'padding' : bigint,
}
export interface CasinoSettings {
  'houseEdgePercentage' : bigint,
  'minDeposit' : bigint,
  'minWithdrawal' : bigint,
  'dealerUsername' : string,
  'currencyName' : string,
}
export type ExternalBlob = Uint8Array;
export interface GameCatalogEntry {
  'title' : string,
  'icon' : ExternalBlob,
  'gameId' : string,
  'description' : string,
  'updatedAt' : Time,
}
export interface GameOutcome {
  'betAmount' : bigint,
  'winAmount' : bigint,
  'timestamp' : Time,
  'gameType' : string,
  'isWin' : boolean,
}
export interface GameSymbolSet {
  'cards' : Array<Symbol>,
  'dice' : Array<Symbol>,
  'slots' : Array<Symbol>,
  'wheel' : Array<Symbol>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteBranding { 'displayName' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Symbol {
  'id' : string,
  'name' : string,
  'updatedAt' : Time,
  'image' : ExternalBlob,
}
export interface ThemeConfig {
  'primaryColor' : string,
  'cardGradient' : string,
  'accentColor' : string,
  'bgGradient' : string,
  'surfaceGradient' : string,
  'navigationGradient' : string,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : string,
  'timestamp' : Time,
  'gameType' : [] | [string],
  'balanceAfter' : bigint,
  'amount' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'lastLoginTime' : Time,
  'username' : string,
  'totalLosses' : bigint,
  'maxStreak' : bigint,
  'diamondsLost' : bigint,
  'totalGamesPlayed' : bigint,
  'diamondsWon' : bigint,
  'totalWins' : bigint,
  'totalDiamondsBet' : bigint,
  'totalDiamondsWon' : bigint,
  'diamondsWagered' : bigint,
  'fastestGameTime' : bigint,
  'hasCompletedWageringRequirement' : boolean,
  'diamondBalance' : bigint,
  'registrationTime' : Time,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGameCatalogEntry' : ActorMethod<[GameCatalogEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAsset' : ActorMethod<[string], undefined>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'getAllAssets' : ActorMethod<[], Array<AppAsset>>,
  'getAllGameCatalogEntries' : ActorMethod<[], Array<GameCatalogEntry>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAsset' : ActorMethod<[string], [] | [AppAsset]>,
  'getBalance' : ActorMethod<[], bigint>,
  'getBannerConfig' : ActorMethod<[], [] | [BannerConfig]>,
  'getBranding' : ActorMethod<[], SiteBranding>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCasinoSettings' : ActorMethod<[], CasinoSettings>,
  'getGameCatalogEntry' : ActorMethod<[string], [] | [GameCatalogEntry]>,
  'getGameHistory' : ActorMethod<[], Array<GameOutcome>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSymbolSet' : ActorMethod<[string], GameSymbolSet>,
  'getThemeConfig' : ActorMethod<[], [] | [ThemeConfig]>,
  'getTopPlayers' : ActorMethod<[], Array<UserProfile>>,
  'getTopPlayersByStreak' : ActorMethod<[], Array<UserProfile>>,
  'getTopPlayersByWins' : ActorMethod<[], Array<UserProfile>>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getTransactionHistoryForUser' : ActorMethod<[Principal], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasCompletedWageringRequirement' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserEligibleForWithdrawal' : ActorMethod<[], boolean>,
  'recordGameOutcome' : ActorMethod<
    [string, bigint, bigint, boolean],
    undefined
  >,
  'registerUser' : ActorMethod<[string], undefined>,
  'removeGameCatalogEntry' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBannerConfig' : ActorMethod<[BannerConfig], undefined>,
  'setCurrencyName' : ActorMethod<[string], undefined>,
  'setDealerUsername' : ActorMethod<[string], undefined>,
  'setHouseEdge' : ActorMethod<[bigint], undefined>,
  'setMinDeposit' : ActorMethod<[bigint], undefined>,
  'setMinWithdrawal' : ActorMethod<[bigint], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setThemeConfig' : ActorMethod<[ThemeConfig], undefined>,
  'storeAsset' : ActorMethod<[AppAsset], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAsset' : ActorMethod<[string, AppAsset], undefined>,
  'updateBranding' : ActorMethod<[SiteBranding], undefined>,
  'updateCasinoSettings' : ActorMethod<[CasinoSettings], undefined>,
  'updateGameCatalogEntry' : ActorMethod<[string, GameCatalogEntry], undefined>,
  'updateSymbolSet' : ActorMethod<[string, GameSymbolSet], undefined>,
  'updateWageredAmount' : ActorMethod<[bigint], undefined>,
  'withdraw' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];