/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CasinoSettings {
  'minDeposit' : bigint,
  'ownerPercentage' : number,
  'dealerUserName' : string,
  'minWithdrawal' : bigint,
  'currencyName' : string,
}
export interface CasinoStats {
  'totalGamesPlayed' : bigint,
  'totalWagers' : bigint,
  'totalDiamondsBet' : bigint,
  'totalDiamondsWon' : bigint,
  'activeGameSessions' : bigint,
}
export interface GameStats {
  'wins' : bigint,
  'losses' : bigint,
  'totalBet' : bigint,
  'totalWin' : bigint,
  'spins' : bigint,
}
export interface GameTransaction {
  'id' : bigint,
  'transactionType' : GameTransactionType,
  'user' : Principal,
  'description' : string,
  'timestamp' : Time,
}
export type GameTransactionType = { 'deposit' : bigint } |
  { 'withdrawal' : bigint } |
  { 'spinOutcome' : { 'betAmount' : bigint, 'winAmount' : bigint } };
export type Time = bigint;
export type TransactionFilter = { 'all' : null } |
  { 'wins' : null } |
  { 'losses' : null } |
  { 'withdrawals' : null } |
  { 'deposits' : null };
export interface TransactionLog { 'log' : GameTransaction }
export interface TransactionLogSearchModifier {
  'transactionFilter' : [] | [TransactionFilter],
  'count' : bigint,
  'offset' : bigint,
  'searchText' : string,
}
export interface UserProfile {
  'username' : string,
  'balance' : bigint,
  'signupBonus' : bigint,
  'totalWagered' : bigint,
  'registrationTime' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings {
  'notificationsEnabled' : boolean,
  'username' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserSettings' : ActorMethod<[UserSettings], undefined>,
  'filterTransactionLog' : ActorMethod<
    [TransactionLogSearchModifier],
    Array<TransactionLog>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCasinoSettings' : ActorMethod<[], [] | [CasinoSettings]>,
  'getCasinoStats' : ActorMethod<[], CasinoStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processPayout' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCasinoSettings' : ActorMethod<[CasinoSettings], undefined>,
  'updateGameStats' : ActorMethod<[GameStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];