/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'username' : IDL.Text,
});
export const TransactionFilter = IDL.Variant({
  'all' : IDL.Null,
  'wins' : IDL.Null,
  'losses' : IDL.Null,
  'withdrawals' : IDL.Null,
  'deposits' : IDL.Null,
});
export const TransactionLogSearchModifier = IDL.Record({
  'transactionFilter' : IDL.Opt(TransactionFilter),
  'count' : IDL.Nat,
  'offset' : IDL.Nat,
  'searchText' : IDL.Text,
});
export const GameTransactionType = IDL.Variant({
  'deposit' : IDL.Nat,
  'withdrawal' : IDL.Nat,
  'spinOutcome' : IDL.Record({ 'betAmount' : IDL.Nat, 'winAmount' : IDL.Nat }),
});
export const Time = IDL.Int;
export const GameTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : GameTransactionType,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const TransactionLog = IDL.Record({ 'log' : GameTransaction });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'signupBonus' : IDL.Nat,
  'totalWagered' : IDL.Nat,
  'registrationTime' : Time,
});
export const CasinoSettings = IDL.Record({
  'minDeposit' : IDL.Nat,
  'ownerPercentage' : IDL.Float64,
  'dealerUserName' : IDL.Text,
  'minWithdrawal' : IDL.Nat,
  'currencyName' : IDL.Text,
});
export const CasinoStats = IDL.Record({
  'totalGamesPlayed' : IDL.Nat,
  'totalWagers' : IDL.Nat,
  'totalDiamondsBet' : IDL.Nat,
  'totalDiamondsWon' : IDL.Nat,
  'activeGameSessions' : IDL.Nat,
});
export const GameStats = IDL.Record({
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalBet' : IDL.Nat,
  'totalWin' : IDL.Nat,
  'spins' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserSettings' : IDL.Func([UserSettings], [], []),
  'filterTransactionLog' : IDL.Func(
      [TransactionLogSearchModifier],
      [IDL.Vec(TransactionLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCasinoSettings' : IDL.Func([], [IDL.Opt(CasinoSettings)], ['query']),
  'getCasinoStats' : IDL.Func([], [CasinoStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processPayout' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCasinoSettings' : IDL.Func([CasinoSettings], [], []),
  'updateGameStats' : IDL.Func([GameStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'username' : IDL.Text,
  });
  const TransactionFilter = IDL.Variant({
    'all' : IDL.Null,
    'wins' : IDL.Null,
    'losses' : IDL.Null,
    'withdrawals' : IDL.Null,
    'deposits' : IDL.Null,
  });
  const TransactionLogSearchModifier = IDL.Record({
    'transactionFilter' : IDL.Opt(TransactionFilter),
    'count' : IDL.Nat,
    'offset' : IDL.Nat,
    'searchText' : IDL.Text,
  });
  const GameTransactionType = IDL.Variant({
    'deposit' : IDL.Nat,
    'withdrawal' : IDL.Nat,
    'spinOutcome' : IDL.Record({
      'betAmount' : IDL.Nat,
      'winAmount' : IDL.Nat,
    }),
  });
  const Time = IDL.Int;
  const GameTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : GameTransactionType,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const TransactionLog = IDL.Record({ 'log' : GameTransaction });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'signupBonus' : IDL.Nat,
    'totalWagered' : IDL.Nat,
    'registrationTime' : Time,
  });
  const CasinoSettings = IDL.Record({
    'minDeposit' : IDL.Nat,
    'ownerPercentage' : IDL.Float64,
    'dealerUserName' : IDL.Text,
    'minWithdrawal' : IDL.Nat,
    'currencyName' : IDL.Text,
  });
  const CasinoStats = IDL.Record({
    'totalGamesPlayed' : IDL.Nat,
    'totalWagers' : IDL.Nat,
    'totalDiamondsBet' : IDL.Nat,
    'totalDiamondsWon' : IDL.Nat,
    'activeGameSessions' : IDL.Nat,
  });
  const GameStats = IDL.Record({
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalBet' : IDL.Nat,
    'totalWin' : IDL.Nat,
    'spins' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserSettings' : IDL.Func([UserSettings], [], []),
    'filterTransactionLog' : IDL.Func(
        [TransactionLogSearchModifier],
        [IDL.Vec(TransactionLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCasinoSettings' : IDL.Func([], [IDL.Opt(CasinoSettings)], ['query']),
    'getCasinoStats' : IDL.Func([], [CasinoStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processPayout' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCasinoSettings' : IDL.Func([CasinoSettings], [], []),
    'updateGameStats' : IDL.Func([GameStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };