/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const GameCatalogEntry = IDL.Record({
  'title' : IDL.Text,
  'icon' : ExternalBlob,
  'gameId' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AppAsset = IDL.Record({
  'assetId' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'assetCategory' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'lastLoginTime' : Time,
  'username' : IDL.Text,
  'totalLosses' : IDL.Nat,
  'maxStreak' : IDL.Nat,
  'diamondsLost' : IDL.Nat,
  'totalGamesPlayed' : IDL.Nat,
  'diamondsWon' : IDL.Nat,
  'totalWins' : IDL.Nat,
  'totalDiamondsBet' : IDL.Nat,
  'totalDiamondsWon' : IDL.Nat,
  'diamondsWagered' : IDL.Nat,
  'fastestGameTime' : IDL.Nat,
  'hasCompletedWageringRequirement' : IDL.Bool,
  'diamondBalance' : IDL.Nat,
  'registrationTime' : Time,
  'currentStreak' : IDL.Nat,
});
export const BannerConfig = IDL.Record({
  'height' : IDL.Nat,
  'backgroundColor' : IDL.Text,
  'objectFit' : IDL.Text,
  'enabled' : IDL.Bool,
  'updatedAt' : Time,
  'destinationUrl' : IDL.Text,
  'bannerImage' : IDL.Opt(ExternalBlob),
  'padding' : IDL.Nat,
});
export const SiteBranding = IDL.Record({ 'displayName' : IDL.Text });
export const CasinoSettings = IDL.Record({
  'houseEdgePercentage' : IDL.Nat,
  'minDeposit' : IDL.Nat,
  'minWithdrawal' : IDL.Nat,
  'dealerUsername' : IDL.Text,
  'currencyName' : IDL.Text,
});
export const GameOutcome = IDL.Record({
  'betAmount' : IDL.Nat,
  'winAmount' : IDL.Nat,
  'timestamp' : Time,
  'gameType' : IDL.Text,
  'isWin' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Symbol = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'updatedAt' : Time,
  'image' : ExternalBlob,
});
export const GameSymbolSet = IDL.Record({
  'cards' : IDL.Vec(Symbol),
  'dice' : IDL.Vec(Symbol),
  'slots' : IDL.Vec(Symbol),
  'wheel' : IDL.Vec(Symbol),
});
export const ThemeConfig = IDL.Record({
  'primaryColor' : IDL.Text,
  'cardGradient' : IDL.Text,
  'accentColor' : IDL.Text,
  'bgGradient' : IDL.Text,
  'surfaceGradient' : IDL.Text,
  'navigationGradient' : IDL.Text,
});
export const Transaction = IDL.Record({
  'transactionType' : IDL.Text,
  'timestamp' : Time,
  'gameType' : IDL.Opt(IDL.Text),
  'balanceAfter' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGameCatalogEntry' : IDL.Func([GameCatalogEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAsset' : IDL.Func([IDL.Text], [], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(AppAsset)], ['query']),
  'getAllGameCatalogEntries' : IDL.Func(
      [],
      [IDL.Vec(GameCatalogEntry)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(AppAsset)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getBannerConfig' : IDL.Func([], [IDL.Opt(BannerConfig)], ['query']),
  'getBranding' : IDL.Func([], [SiteBranding], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCasinoSettings' : IDL.Func([], [CasinoSettings], ['query']),
  'getGameCatalogEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GameCatalogEntry)],
      ['query'],
    ),
  'getGameHistory' : IDL.Func([], [IDL.Vec(GameOutcome)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSymbolSet' : IDL.Func([IDL.Text], [GameSymbolSet], ['query']),
  'getThemeConfig' : IDL.Func([], [IDL.Opt(ThemeConfig)], ['query']),
  'getTopPlayers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTopPlayersByStreak' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTopPlayersByWins' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTransactionHistoryForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCompletedWageringRequirement' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserEligibleForWithdrawal' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGameOutcome' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'removeGameCatalogEntry' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBannerConfig' : IDL.Func([BannerConfig], [], []),
  'setCurrencyName' : IDL.Func([IDL.Text], [], []),
  'setDealerUsername' : IDL.Func([IDL.Text], [], []),
  'setHouseEdge' : IDL.Func([IDL.Nat], [], []),
  'setMinDeposit' : IDL.Func([IDL.Nat], [], []),
  'setMinWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setThemeConfig' : IDL.Func([ThemeConfig], [], []),
  'storeAsset' : IDL.Func([AppAsset], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAsset' : IDL.Func([IDL.Text, AppAsset], [], []),
  'updateBranding' : IDL.Func([SiteBranding], [], []),
  'updateCasinoSettings' : IDL.Func([CasinoSettings], [], []),
  'updateGameCatalogEntry' : IDL.Func([IDL.Text, GameCatalogEntry], [], []),
  'updateSymbolSet' : IDL.Func([IDL.Text, GameSymbolSet], [], []),
  'updateWageredAmount' : IDL.Func([IDL.Nat], [], []),
  'withdraw' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const GameCatalogEntry = IDL.Record({
    'title' : IDL.Text,
    'icon' : ExternalBlob,
    'gameId' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AppAsset = IDL.Record({
    'assetId' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'assetCategory' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'lastLoginTime' : Time,
    'username' : IDL.Text,
    'totalLosses' : IDL.Nat,
    'maxStreak' : IDL.Nat,
    'diamondsLost' : IDL.Nat,
    'totalGamesPlayed' : IDL.Nat,
    'diamondsWon' : IDL.Nat,
    'totalWins' : IDL.Nat,
    'totalDiamondsBet' : IDL.Nat,
    'totalDiamondsWon' : IDL.Nat,
    'diamondsWagered' : IDL.Nat,
    'fastestGameTime' : IDL.Nat,
    'hasCompletedWageringRequirement' : IDL.Bool,
    'diamondBalance' : IDL.Nat,
    'registrationTime' : Time,
    'currentStreak' : IDL.Nat,
  });
  const BannerConfig = IDL.Record({
    'height' : IDL.Nat,
    'backgroundColor' : IDL.Text,
    'objectFit' : IDL.Text,
    'enabled' : IDL.Bool,
    'updatedAt' : Time,
    'destinationUrl' : IDL.Text,
    'bannerImage' : IDL.Opt(ExternalBlob),
    'padding' : IDL.Nat,
  });
  const SiteBranding = IDL.Record({ 'displayName' : IDL.Text });
  const CasinoSettings = IDL.Record({
    'houseEdgePercentage' : IDL.Nat,
    'minDeposit' : IDL.Nat,
    'minWithdrawal' : IDL.Nat,
    'dealerUsername' : IDL.Text,
    'currencyName' : IDL.Text,
  });
  const GameOutcome = IDL.Record({
    'betAmount' : IDL.Nat,
    'winAmount' : IDL.Nat,
    'timestamp' : Time,
    'gameType' : IDL.Text,
    'isWin' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Symbol = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'updatedAt' : Time,
    'image' : ExternalBlob,
  });
  const GameSymbolSet = IDL.Record({
    'cards' : IDL.Vec(Symbol),
    'dice' : IDL.Vec(Symbol),
    'slots' : IDL.Vec(Symbol),
    'wheel' : IDL.Vec(Symbol),
  });
  const ThemeConfig = IDL.Record({
    'primaryColor' : IDL.Text,
    'cardGradient' : IDL.Text,
    'accentColor' : IDL.Text,
    'bgGradient' : IDL.Text,
    'surfaceGradient' : IDL.Text,
    'navigationGradient' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'transactionType' : IDL.Text,
    'timestamp' : Time,
    'gameType' : IDL.Opt(IDL.Text),
    'balanceAfter' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGameCatalogEntry' : IDL.Func([GameCatalogEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAsset' : IDL.Func([IDL.Text], [], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(AppAsset)], ['query']),
    'getAllGameCatalogEntries' : IDL.Func(
        [],
        [IDL.Vec(GameCatalogEntry)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAsset' : IDL.Func([IDL.Text], [IDL.Opt(AppAsset)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getBannerConfig' : IDL.Func([], [IDL.Opt(BannerConfig)], ['query']),
    'getBranding' : IDL.Func([], [SiteBranding], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCasinoSettings' : IDL.Func([], [CasinoSettings], ['query']),
    'getGameCatalogEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GameCatalogEntry)],
        ['query'],
      ),
    'getGameHistory' : IDL.Func([], [IDL.Vec(GameOutcome)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSymbolSet' : IDL.Func([IDL.Text], [GameSymbolSet], ['query']),
    'getThemeConfig' : IDL.Func([], [IDL.Opt(ThemeConfig)], ['query']),
    'getTopPlayers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTopPlayersByStreak' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTopPlayersByWins' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTransactionHistoryForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCompletedWageringRequirement' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserEligibleForWithdrawal' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGameOutcome' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'removeGameCatalogEntry' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBannerConfig' : IDL.Func([BannerConfig], [], []),
    'setCurrencyName' : IDL.Func([IDL.Text], [], []),
    'setDealerUsername' : IDL.Func([IDL.Text], [], []),
    'setHouseEdge' : IDL.Func([IDL.Nat], [], []),
    'setMinDeposit' : IDL.Func([IDL.Nat], [], []),
    'setMinWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setThemeConfig' : IDL.Func([ThemeConfig], [], []),
    'storeAsset' : IDL.Func([AppAsset], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAsset' : IDL.Func([IDL.Text, AppAsset], [], []),
    'updateBranding' : IDL.Func([SiteBranding], [], []),
    'updateCasinoSettings' : IDL.Func([CasinoSettings], [], []),
    'updateGameCatalogEntry' : IDL.Func([IDL.Text, GameCatalogEntry], [], []),
    'updateSymbolSet' : IDL.Func([IDL.Text, GameSymbolSet], [], []),
    'updateWageredAmount' : IDL.Func([IDL.Nat], [], []),
    'withdraw' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };